### ISSUE TITLE
Performance regression from v2.8 to v2.10

### ISSUE THREAD

**Issue by shehzan10** [clMathLibraries/clFFT#134] opened 2016-03-07 19:20 UTC
We are seeing a performance regression from v2.8 to v2.10. We noticed this only on AMD GPUs (testing on FirePro W8100). NVIDIA GPUs don't show any difference in performance between the versions.

 Size             | v2.8 Time | v2.10 Time
-----------------|-------------- |-----------------
1024 x 1024 | 0.400 ms | 0.385 ms
2048 x 2048 | 1.365 ms | 2.300 ms

Attached: Modified version of examples/fft2d.c to print the time taken (renamed extension from cpp -> txt).

[fft2d.txt](https://github.com/clMathLibraries/clFFT/files/161935/fft2d.txt)

**Comment by pavanky** [comment] 2016-03-07 20:00
@bragadeesh We only benchmarked 2D FFT so we are not sure if it affects any other configurations. From what we have noticed it affects both Tahiti and Hawaii architectures.

**Comment by bragadeesh** [comment] 2016-03-08 06:51
I can reproduce this on my W9100; Hmmm, let me see what is going on ..

**Comment by bragadeesh** [comment] 2016-03-09 05:58
This is a result of transpose kernel getting replaced. After 2.8 release, we retired a variant (Transpose_VLIW) of transpose generator and replaced wherever it was used with other variants. Looks like a bit more work is needed to get this performance problem fixed.

**Comment by bragadeesh** [comment] 2016-03-10 00:14
Hey guys, I made commit cf0199c580d7297f2ab64cc76637cbc9887feb57 to fix the performance regression; let me know if you can verify. Note this is in develop branch and has not gone through full testing.

**Comment by pavanky** [comment] 2016-03-10 00:32
@bragadeesh I tested this using arrayfire (not the stand alone code here). Here are the benchmarks with 2.8, 2.10 and develop on a 390x.

**v2.8**

```
 128 x  128:    45 Gflops
 256 x  256:    98 Gflops
 512 x  512:   171 Gflops
1024 x 1024:   283 Gflops
2048 x 2048:   376 Gflops
4096 x 4096:   396 Gflops
```

**v2.10**
```
 128 x  128:    41 Gflops
 256 x  256:   106 Gflops
 512 x  512:   179 Gflops
1024 x 1024:   278 Gflops
2048 x 2048:   230 Gflops
4096 x 4096:    92 Gflops
```

**develop**

```
 128 x  128:    44 Gflops
 256 x  256:    95 Gflops
 512 x  512:   196 Gflops
1024 x 1024:   318 Gflops
2048 x 2048:   424 Gflops
4096 x 4096:   425 Gflops
```

Looks like the performance improves improves by a significant amount compared to 2.8 for sizes >= 1024. But is slower by a bit for sizes <= 512.

FYI, We are using 10 * N * N * log2(N) for FLOP count (Where N is the width).

**Comment by pavanky** [comment] 2016-03-10 01:28
Also ran our tests on a AMD R9 390x and NVIDIA GTX 950.  They seem to pass all fft based tests :+1:

**Comment by pavanky** [comment] 2016-03-10 01:34
BTW, I also benchmarked real to complex transform for good measure. This does not seem to have gone through any performance regressions since 2.8.

**Comment by bragadeesh** [comment] 2016-03-10 06:35
@pavanky thanks for all the testing on your end. I guess you on your side, you have a process to selectively choose which clFFT you use? Can you consume the develop version in the meantime or do you need to wait for a tagged release?

**Comment by pavanky** [comment] 2016-03-10 06:49
@bragadeesh We maintain a branch in our fork of clFFT which points to a commit that passes all our tests. Right now it points to the latest master. We can update to develop and see if it passes on all of our test architectures. 

BTW Is this all your passing tests on your end ?

**Comment by bragadeesh** [comment] 2016-03-16 00:35
Tests passed on our side; I have made a point release:
https://github.com/clMathLibraries/clFFT/releases/tag/v2.10.1

**Comment by shehzan10** [comment] 2016-03-16 16:50
Looks like the tests are passing on AMD hardware.
There is 1 test failing on NVIDIA GPUs on Windows and Linux.
Builds:
http://ci.arrayfire.org/job/clMathLibraries/job/clFFT-Windows/18/
http://ci.arrayfire.org/view/All/job/clMathLibraries/job/clFFT-Linux/25/

PS. You might have an issue opening the XML files. In that case, right click and select view source.

**Comment by bragadeesh** [comment] 2016-03-18 22:13
Closing this issue, as it pertains to perf regression only

**Closed by bragadeesh** 2016-03-18 22:13 UTC
