### ISSUE TITLE
Some install targets are now disabled in v2.8

### ISSUE THREAD

**Issue by ghisvail** [clMathLibraries/clFFT#114] opened 2015-10-22 23:42 UTC
Whilst attempting to refresh the Debian packaging with `v2.8`, I made the unpleasant discovery that the client binary and pkg-config file are no-longer installed.

Any particular reason for this? This issue creates additional maintenance burden which I would rather do without. Please consider releasing a bugfix release with the old behaviour back.

Thanks.

**Comment by bragadeesh** [comment] 2015-10-23 15:44
The reason for removing client is that many users wanted our package/install step to include only the library and examples. The client and test are not used by regular users of the library and so we decide to skip it. We did not mean to catch you by surprise, and thanks for the work you are doing.

Which file are you referring to by pkg-config? Is there a way that you could control this behavior with specific cmake variables? thereby you can enable them only for debian packaging needs, and by default it remains turned off. Would you have cycles to provide a PR?.

**Comment by ghisvail** [comment] 2015-10-23 15:54
> The reason for removing client is that many users wanted our package/install step to include only the library and examples. The client and test are not used by regular users of the library and so we decide to skip it. We did not mean to catch you by surprise, and thanks for the work you are doing.

A word in the [tag summary](https://github.com/clMathLibraries/clFFT/releases) would have been nice.

If you meant to provide a more granular choice of installation, fine do it. That's what I expect from options like `BUILD_DOCS`, `BUILD_RUNTIME`, `BUILD_CLIENTS`...

But a `BUILD_CLIENTS` that actually builds the executable but does *not* install it, I completely fail to understand the purpose of this.

> Which file are you referring to by pkg-config?

The `clFFT.pc` file. It has been nicely commented out by an earlier commit. At least the code is still there in case it should be re-activated in the future.

> Is there a way that you could control this behavior with specific cmake variables?

Again, isn't it what the `BUILD_*` options are supposed to be doing?

> thereby you can enable them only for debian packaging needs, and by default it remains turned off.

I would be fine with that.

> Would you have cycles to provide a PR?

If that does not get commented out later, maybe.

My apologize for the dry tone, but this is very annoying. I hope I won't get the same surprise on the next release of `clBLAS` too.

**Comment by ghisvail** [comment] 2015-10-29 15:11
#116 addresses the installation of the missing pkg-config file.

**Comment by ghisvail** [comment] 2015-10-29 15:18
> The reason for removing client is that many users wanted our package/install step to include only the library and examples. The client and test are not used by regular users of the library and so we decide to skip it. We did not mean to catch you by surprise, and thanks for the work you are doing.

Based on this statement, that would mean the default build options should be `BUILD_RUNTIME=ON`, `BUILD_EXAMPLES=ON` and the rest turned off right?

**Comment by marbre** [comment] 2015-10-31 10:42
I agree with @ghisvail, building the client but don't installing it normally isn't the expected behaviour (see my comments on commit https://github.com/clMathLibraries/clFFT/commit/d0379cc5e1eb882cd47a0614b1a482d4305388f4). If I don't want to install and to use it, I definitely can/want to save the build time by setting `BUILD_CLIENT=OFF`.

Regarding the default build options. These should IMHO be set in the [CMakeLists.txt](https://github.com/clMathLibraries/clFFT/blob/master/src/CMakeLists.txt), but there all options are enabled. Maybe this should be adjusted to the "defaults".

**Comment by bragadeesh** [comment] 2015-11-03 05:51
Issues addressed with recent commits in develop branch; closing this for now.

**Closed by bragadeesh** 2015-11-03 05:51 UTC
