### ISSUE TITLE
OSX clFFT AMD FFT results in blank FFT

### ISSUE THREAD

**Issue by Astro-Nick** [clMathLibraries/clFFT#44] opened 2014-08-20 09:08 UTC
Hi, firstly - many thanks for maintaining and enhancing this library.

I've got a FFT based image alignment working with the GPU for astronomy - however I've noted that when given specific sizes of 2D FFT (that are allowed according to the plan checking dims in the plan source) that everything works except no FFT is produced.

The 2D 3645x450 FFT bakes, executes the encoding but does not pass an error or log an error to the Console log.

I'm using OSX 10.8.5 on a MBP - using the AMD Radeon HD 6750M 1024 MB GPU and will shortly be upgrading the OSX (which I know has some OpenCL "improvements").

I know that nVidia cards had some issues with texture sizes but I wasn't aware of AMD ones.

The same output debug printing route works for the other FFT plan in use - both inputs and FFTs produced result in FFT images. Input printed immediately before the FFT enqueuing shows data input but a blank output (after executing clFinish()).

Any ideas? It sounds like either the code or driver is failing quietly. Looking at the clFFT sources I think it's probably more a driver issue.

**Comment by kknox** [comment] 2015-01-30 20:15
Hi @Astro-Nick 
I wanted to let you know that last week we made a check-in that fixed the unit test failures we were seeing with checkin clMathLibraries/clFFT@b6501dbd37a021dfc788d468cfd7a67733f63e3b.  

This ended up being a difficult to find event leak in our unit test framework, and does not involve the MacOSX runtime.  So, we are kind of back to square 1, where I do not have code to reproduce the issue you reported.  My hope that the failure I was chasing was the same as the failure you reported  is now proven false. 

If you would like me to continue chasing your issue, i need a runable repro case.  You attempted to post something above in this thread, but it was unusable because of the markdown mangling.  I'll close this issue in a few days if I don't hear anything.

**Comment by Astro-Nick** [comment] 2015-01-30 22:29
Hi,
I'd still like to get this fixed - only sand in the oil is that my MBP's Radeon 6750M has died, I only have a a mac mini (GF 9400 and a MBA) that don't have OpenCL 1.1+ for Yosemite 10.10 SDK.

It's not fixed with the move to pure OpenCL, however I don't have the ability to run the code now (the machine works but will simply restart if the GPU switch to the 6750M is attempted.

I have a few things I need todo this week, however I can try but I can't guarantee having a test example available for obvious reasons.

I don't think this was related with the MBP's failing GPU as there's no evidence either way.

**Comment by kknox** [comment] 2015-02-26 17:43
Closing due to inactivity; please re-open when you can attach/provide a repro case

**Closed by kknox** 2015-02-26 17:43 UTC
Labels: Apple, bug, GPU, OSX

**Comment by Astro-Nick** [comment] 2015-03-29 14:21
Hi folks, sorry for the delay. Job hunt continuing - had a great time under the stars so got a bit of time to look again.

I've started continuing work on this after sequentially prodding things - I think it's a data synchronisation issue. I have managed to replicate this again using the application (not a repo case) and by making a single change causes.
I noted that using a map to write a graphical file caused the FFT to work, however without the mapping - the result was a blank result.


// without the next two lines of code the FFT does not produce a result..
    clInstance->textureManagement()->forceDataSync(inputReal, fftDimensions);
    clInstance->textureManagement()->forceDataSync(inputComplex, fftDimensions);
// end of addition
    
    clfftStatus clErr= clfftEnqueueTransform(fftPlan,CLFFT_FORWARD, 1, clInstance->commandQueue(),
                                             0, NULL, clInstance->synchronisationLock(),
                                             input, output, tmpBuffer);
    
    clWaitForEvents(1, clInstance->synchronisationLock());
    
    if(clErr!=CL_SUCCESS)
        Logger::debug("fft error = %i", clErr);

// without the next two lines of code the FFT does not produce a result..
    clInstance->textureManagement()->forceDataSync(outputReal, fftDimensions);
    clInstance->textureManagement()->forceDataSync(outputComplex, fftDimensions);
// end of addition

As the project required to create this is a bit involved - I'll pass you a binary with a GUI flag to enable/disable the additional "forceDataSync" operations. The result should be that with the tools you have available to you on OS X in driver development, perhaps it can help locate the issue.
I'll then pass you the link.

**Comment by Astro-Nick** [comment] 2015-05-09 08:55
Ignore the above.. it's a red herring. I'm back to square one on this.

Just to say I found a way around this - my pipeline is a C++ class based system in which the classes provide the calling kernel sequence for texture references, with the pipeline managing textures and kernels in memory.
I ended up refactoring so the FFT class was an interface and producing a clFFT and FFTW implementation - this allows full CPU OpenCL with FFTW, GPU/CPU hybrid OpenCL with FFTW and full GPU with clFFT. (also CPU with GPU clFFT is possible). The pipeline is working again once I switch to FFTW for the FFT steps - it's odd because the clFFT works for the curve fitting for another part of the pipeline but that is 1D and doesn't have large dimensions..
So if anyone else has the same issue - I would suggest using this approach if you're on OS X only.

On the plus point - I did find an array under run/overrun running the OpenCL in GPU - but that still hasn't solved my clFFT issue of some texture sizes causing zero result to be returned.

I have come across a report of a bug with constants that could contribute to this - but I don't know if it's the cause (just speculation) - it appears that myArray[offset+constant] returned zero and not the content of the location. So myArray[offset+...+1] fails - something that the generators have. 

Either way - I think the next step is for me to create a simple command line app for the OpenCL pipeline to sit in and process some files. I'll have to get native install of Linux on the MBP.. more time wasted (this is the bit that annoys me).

**Comment by Astro-Nick** [comment] 2015-05-21 14:59
Just to give an update on this - I've spend a few days getting ubuntu installed on the MBP using an external USB hard drive.. however now the linux AMD drivers are having issues (i.e. install gflrx and the desktop hangs) which is supposedly a known issue with switchable bi-gpu machines. Supposedly some people have it working, others say it's impossible to resolve.
Linux AMD CodeXL naturally detects an intel CPU and the intel 3000HD in use, as the gflrx drivers aren't installed and disables support.. so I took that as no execution of OpenCL... 
At this rate I may be tempted to make a USB windows USB install and do the radeon drivers there...
