### ISSUE TITLE
Bypass memory intensive testcases

### ISSUE THREAD

**Issue by ghisvail** [clMathLibraries/clFFT#160] opened 2016-08-04 09:08 UTC
Running the testsuite with `pocl` as the OpenCL driver, I get an unusually large memory consumption from the testsuite (\*4M\* tests in particular).

I ended up force-stopping the testsuite with CTRL-C, which fortunately released all the memory (see screenshots below). Since there is not apparent way to turn off this particular test, this becomes a problem, as it requires me to patch the code of the testsuite to prevent memory intensive testcases from executing.

Please consider providing a mechanism to bypass the execution of memory intensive testcases, either at build time or at run time.

Info output:
```
clFFT client API version:  2.12.1
clFFT runtime version:     2.12.1

    CL_PLATFORM_PROFILE:     FULL_PROFILE
    CL_PLATFORM_VERSION:     OpenCL 2.0 pocl 0.13, LLVM 3.8.1
    CL_PLATFORM_NAME:        Portable Computing Language
    CL_PLATFORM_VENDOR:      The pocl project
    CL_PLATFORM_EXTENSIONS:  cl_khr_icd

    CL_DEVICE_NAME:                      pthread-Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
    CL_DEVICE_VERSION:                   OpenCL 2.0 pocl
    CL_DRIVER_VERSION:                   0.13
    CL_DEVICE_TYPE:                      defaultCPU
    CL_DEVICE_MAX_CLOCK_FREQUENCY:       3300
    CL_DEVICE_ADDRESS_BITS:              64
    CL_DEVICE_AVAILABLE:                 TRUE
    CL_DEVICE_COMPILER_AVAILABLE:        TRUE
    CL_DEVICE_OPENCL_C_VERSION:          OpenCL C 2.0
    CL_DEVICE_MAX_WORK_GROUP_SIZE:       4096
    CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:  3
                         Dimension[ 0 ]  4096
                         Dimension[ 1 ]  4096
                         Dimension[ 2 ]  4096
    CL_DEVICE_HOST_UNIFIED_MEMORY:       TRUE
    CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:  10424524800 ( 10180200 KB )
    CL_DEVICE_LOCAL_MEM_SIZE:            10424524800 ( 10180200 KB )
    CL_DEVICE_GLOBAL_MEM_SIZE:           10424524800 ( 9941 MB )
    CL_DEVICE_MAX_MEM_ALLOC_SIZE:        10424524800 ( 9941 MB )
    CL_DEVICE_EXTENSIONS:                cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir cl_khr_int64 cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics

Result comparison tolerance is 0.001
Result comparison RMSE relative tolerance is 2e-05
Random test's seed is 162300751
```

Test output (with --short):
![screenshot from 2016-08-04 09-53-22](https://cloud.githubusercontent.com/assets/1964655/17396274/8dd3bae0-5a2a-11e6-99f6-f648b5e3d004.png)
![screenshot from 2016-08-04 09-54-04](https://cloud.githubusercontent.com/assets/1964655/17396293/a6ee4838-5a2a-11e6-8a36-2e3f8aaf253e.png)

**Comment by bragadeesh** [comment] 2016-08-09 16:57
There is a mechanism (using C++ exceptions) in the test suite to abort a test safely for large memory test cases if 'clCreateBuffer' fails. The test is ended and the test suite continues with the next test. An example is shown below.

In your case from your CL info, the memory availability is large enough that none of the tests would face this issue. There is some other problem that is going on.

////

[----------] 1 test from accuracy_test_pow2_precallback_single
[ RUN      ] accuracy_test_pow2_precallback_single.large_1D_4M_in_place_real_to_hermitian_interleaved
[       OK ] accuracy_test_pow2_precallback_single.large_1D_4M_in_place_real_to_hermitian_interleaved (8624 ms)
[----------] 1 test from accuracy_test_pow2_precallback_single (8626 ms total)

[----------] 1 test from accuracy_test_pow2_precallback_double
[ RUN      ] accuracy_test_pow2_precallback_double.large_1D_4M_in_place_real_to_hermitian_interleaved
Exception occurred during clfftEnqueueTransformc:\work\src\github\clfft\src\tests\cl_transform.h920
--- Exception caught ---
Data set is too large for this device -- skipping test
[       OK ] accuracy_test_pow2_precallback_double.large_1D_4M_in_place_real_to_hermitian_interleaved (8416 ms)
[----------] 1 test from accuracy_test_pow2_precallback_double (8418 ms total)

**Comment by bragadeesh** [comment] 2016-08-09 17:11
I am closing this issue since the feature being requested is already there; lets continue in the #161 thread to see what the problem is.

**Closed by bragadeesh** 2016-08-09 17:11 UTC
